/* eslint-disable @typescript-eslint/no-explicit-any */
import fs from "node:fs";
import path from "node:path";
import type {
  HTTPMethod,
  McpTool,
  NavigationGroup,
  OpenAPISpec,
  ParsedEndpoint,
  RestRoute,
  SearchItem,
} from "./types";
import { resolveRefs } from "./resolve-refs";

// Generated artifacts — see scripts/gen-api-docs.py. Committed to the repo and
// regenerated by the Pages workflow before this app is built.
const API_DIR = path.join(process.cwd(), "..", "landing", "api");

function readJSON<T>(file: string, fallback: T): T {
  const p = path.join(API_DIR, file);
  if (!fs.existsSync(p)) return fallback;
  return JSON.parse(fs.readFileSync(p, "utf8")) as T;
}

/** Host port for the local REST API server (MicropodAPIMain default). */
export const REST_BASE_URL = "http://localhost:45454";

// ---------------------------------------------------------------------------
// REST routes (rest-routes.json — extracted from APIHandlers.swift)
// ---------------------------------------------------------------------------

function restGroup(p: string): string {
  if (p === "/health" || p === "/metrics") return "Service";
  const seg = p.split("/").filter(Boolean)[1] ?? "other";
  const names: Record<string, string> = {
    containers: "Containers",
    images: "Images",
    volumes: "Volumes",
    networks: "Networks",
    compose: "Compose",
    system: "System",
    config: "Config",
    stats: "Stats",
    usage: "Usage",
    exec: "Exec",
  };
  return names[seg] ?? seg[0].toUpperCase() + seg.slice(1);
}

export function restRouteId(method: string, p: string): string {
  const slug = p
    .replace(/\//g, "-")
    .replace(/[{}]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return `${method.toLowerCase()}-${slug}`;
}

export function loadRestRoutes(): RestRoute[] {
  const raw = readJSON<Array<{ method: string; path: string; description: string }>>(
    "rest-routes.json",
    [],
  );
  return raw.map((r) => ({
    id: restRouteId(r.method, r.path),
    method: r.method as HTTPMethod,
    path: r.path,
    description: r.description,
    group: restGroup(r.path),
    pathParams: [...r.path.matchAll(/\{(\w+)\}/g)].map((m) => m[1]),
  }));
}

export function getRestRoute(id: string): RestRoute | undefined {
  return loadRestRoutes().find((r) => r.id === id);
}

// ---------------------------------------------------------------------------
// MCP tools (mcp-tools.json — captured from a live tools/list)
// ---------------------------------------------------------------------------

const MCP_GROUP_ORDER = [
  "containers",
  "images",
  "volumes",
  "shares",
  "networks",
  "compose",
  "system",
  "cache",
];

function mcpGroup(name: string): string {
  if (name.startsWith("compose")) return "compose";
  if (name.startsWith("share")) return "shares";
  if (name.startsWith("volume") || name === "df") return "volumes";
  if (name.startsWith("list_image") || name === "pull" || name === "push") return "images";
  if (name.startsWith("list_network")) return "networks";
  if (name.startsWith("update") || name === "status" || name === "stats") return "system";
  if (name === "build_cache_stats") return "cache";
  return "containers";
}

export function loadMcpTools(): McpTool[] {
  const raw = readJSON<Array<{ name: string; description?: string; inputSchema?: any }>>(
    "mcp-tools.json",
    [],
  );
  return raw
    .map((t) => ({
      name: t.name,
      description: t.description ?? "",
      inputSchema: t.inputSchema ?? {},
      group: mcpGroup(t.name),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function mcpGroups(tools: McpTool[]): { title: string; tools: McpTool[] }[] {
  const map = new Map<string, McpTool[]>();
  for (const t of tools) {
    const list = map.get(t.group) ?? [];
    list.push(t);
    map.set(t.group, list);
  }
  return MCP_GROUP_ORDER.filter((g) => map.has(g)).map((g) => ({
    title: g[0].toUpperCase() + g.slice(1),
    tools: map.get(g)!,
  }));
}

export function getMcpTool(name: string): McpTool | undefined {
  return loadMcpTools().find((t) => t.name === name);
}

// ---------------------------------------------------------------------------
// Connect/gRPC OpenAPI specs (buf -> connect-openapi plugin)
// ---------------------------------------------------------------------------

const CONNECT_SPECS = [
  {
    file: "micropod/v1/api.openapi.json",
    service: "micropod.v1.MicropodService",
    title: "MicropodService",
    blurb:
      "Connect-RPC control surface mounted by MicropodAPI (and the Go daemon at api/). Connect JSON over HTTP — same messages as the protobuf contract.",
  },
  {
    file: "com/apple/containerization/sandbox/v3/sandbox_context.openapi.json",
    service: "com.apple.containerization.sandbox.v3.SandboxContext",
    title: "SandboxContext",
    blurb:
      "The vminitd guest contract (vendored from apple/containerization). Served over vsock port 1024 inside each container VM — not reachable over host HTTP.",
  },
] as const;

export interface ConnectService {
  file: string;
  service: string;
  title: string;
  blurb: string;
  spec: OpenAPISpec;
}

function parseSpec(file: string): OpenAPISpec {
  const raw = readJSON<any>(file, null);
  if (!raw) {
    return {
      file,
      info: { title: "API", version: "0" },
      endpoints: [],
      groups: [],
      schemaCount: 0,
    };
  }

  const schemas = raw.components?.schemas ?? {};
  const endpoints: ParsedEndpoint[] = [];

  for (const [pathKey, methods] of Object.entries<any>(raw.paths ?? {})) {
    for (const [method, operation] of Object.entries<any>(methods)) {
      if (typeof operation !== "object") continue;
      const service = (operation.tags?.[0] as string | undefined) ?? "unknown";
      endpoints.push({
        id: `${method}-${pathKey.replace(/\//g, "-").replace(/[{}]/g, "")}`.toLowerCase(),
        method: method.toUpperCase() as HTTPMethod,
        path: pathKey,
        service,
        summary: operation.summary,
        description: operation.description,
        operationId: operation.operationId,
        parameters: resolveRefs(operation.parameters ?? [], schemas),
        requestBody: resolveRefs(operation.requestBody, schemas),
        responses: resolveRefs(operation.responses ?? {}, schemas),
      });
    }
  }

  const byService = new Map<string, ParsedEndpoint[]>();
  for (const e of endpoints) {
    const list = byService.get(e.service) ?? [];
    list.push(e);
    byService.set(e.service, list);
  }
  const groups: NavigationGroup[] = [...byService.entries()].map(([svc, eps]) => ({
    title: svc.split(".").pop() ?? svc,
    endpoints: eps,
  }));

  return {
    file,
    info: {
      title: raw.info?.title ?? file,
      description: raw.info?.description,
      version: raw.info?.version ?? "0",
    },
    endpoints,
    groups,
    schemaCount: Object.keys(schemas).length,
  };
}

export function loadConnectServices(): ConnectService[] {
  return CONNECT_SPECS.map((s) => ({ ...s, spec: parseSpec(s.file) }));
}

export function getConnectEndpoint(id: string): {
  endpoint: ParsedEndpoint;
  service: ConnectService;
} | undefined {
  for (const service of loadConnectServices()) {
    const endpoint = service.spec.endpoints.find((e) => e.id === id);
    if (endpoint) return { endpoint, service };
  }
  return undefined;
}

// ---------------------------------------------------------------------------
// Search index (all surfaces, for the header Cmd+K dialog)
// ---------------------------------------------------------------------------

export function buildSearchIndex(): SearchItem[] {
  const items: SearchItem[] = [
    {
      kind: "SDK",
      title: "Client SDKs",
      subtitle: "Go, TypeScript, and Swift clients — retry, timeouts, OpenTelemetry",
      href: "/sdk/",
    },
  ];
  for (const r of loadRestRoutes()) {
    items.push({
      kind: "REST",
      title: `${r.method} ${r.path}`,
      subtitle: r.description,
      href: `/rest/${r.id}/`,
      method: r.method,
    });
  }
  for (const svc of loadConnectServices()) {
    for (const e of svc.spec.endpoints) {
      items.push({
        kind: "Connect",
        title: e.summary ?? e.path,
        subtitle: `${svc.title} · ${e.description ?? ""}`.trim(),
        href: `/grpc/${e.id}/`,
        method: e.method,
      });
    }
  }
  for (const t of loadMcpTools()) {
    items.push({
      kind: "MCP",
      title: t.name,
      subtitle: t.description,
      href: `/mcp/${t.name}/`,
    });
  }
  return items;
}
