import React from "react";
import type { Metadata } from "next";
import { ArrowUpRight, FileCode2 } from "lucide-react";

export const metadata: Metadata = {
  title: "Protobuf reference",
};

const FILES = [
  "proto/micropod/v1/api.proto",
  "proto/micropod/v1/container.proto",
  "proto/micropod/v1/image.proto",
  "proto/micropod/v1/system.proto",
  "proto/micropod/v1/compose.proto",
  "proto/com/apple/containerization/sandbox/v3/sandbox_context.proto",
];

export default function ProtoPage() {
  return (
    <div className="mx-auto max-w-3xl space-y-8 px-6 py-10 md:px-10">
      <div className="space-y-3">
        <h1 className="text-3xl font-bold tracking-tight">Protobuf reference</h1>
        <p className="text-muted">
          The proto files are the source of truth for the Connect services, the
          Go daemon bindings (<code className="font-mono text-xs">api/gen/</code>),
          and the vminitd guest contract. The full generated reference — every
          message, field, and enum — is published as a standalone document.
        </p>
      </div>

      <a
        href="/micropod/api/specs/proto-reference.html"
        className="group flex items-center justify-between rounded-lg border border-border bg-card p-5 transition-colors hover:border-primary/50"
      >
        <div className="flex items-center gap-3">
          <FileCode2 className="h-5 w-5 text-primary" />
          <div>
            <h2 className="font-semibold">proto-reference.html</h2>
            <p className="text-sm text-muted">
              Generated by the pseudomuto-doc buf plugin — self-contained HTML.
            </p>
          </div>
        </div>
        <ArrowUpRight className="h-4 w-4 text-muted transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" />
      </a>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold">Source files</h2>
        <ul className="divide-y divide-border overflow-hidden rounded-lg border border-border">
          {FILES.map((f) => (
            <li key={f}>
              <a
                href={`https://github.com/castlemilk/micropod/blob/master/${f}`}
                className="flex items-center bg-card px-4 py-2.5 font-mono text-xs text-primary hover:bg-secondary/50 hover:underline"
              >
                {f}
              </a>
            </li>
          ))}
        </ul>
      </section>
    </div>
  );
}
